### ISSUE TITLE
.

### ISSUE THREAD

**Issue by aa1008611** [geovex/tgp#2]
go mod download

go build ./cmd/tgp

Input not responding，Can you introduce the environment in detail? Thank you.

**Comment by geovex** [comment]
I tried on my vps, `go build ` took nearly 30seconds to compile. Go compiler is not so fast when build cache is clean. You can try `go build -v ./cmd/tgp` to get some progress.
Also I'll mention in readme that you need go 1.20

**Comment by aa1008611** [comment]
System clear display go command not found  How to install it

**Comment by geovex** [comment]
Obviously you need to at least install go compiler to build this. I don't know what system you are using, So I can't give consistent advice. We can convert this issue to discussion and talk about details.

**Comment by aa1008611** [comment]
debian 和 centos

**Comment by aa1008611** [comment]
have tg group?

**Comment by aa1008611** [comment]
centos How does the system install go

**Comment by aa1008611** [comment]
The DC 5 data center is not connected

**Comment by aa1008611** [comment]
After obtaining input from adtag, restart the program/wait for a long time without any response, do not display sponsors

**Comment by geovex** [comment]
Discussion moved to (#3 )
